// Code generated by mockery v2.20.2. DO NOT EDIT.

package main

import (
	context "context"
	sync "sync"

	mock "github.com/stretchr/testify/mock"
)

// MockKafkaConsumerProcessorInterface is an autogenerated mock type for the KafkaConsumerProcessorInterface type
type MockKafkaConsumerProcessorInterface struct {
	mock.Mock
}

// Disable provides a mock function with given fields:
func (_m *MockKafkaConsumerProcessorInterface) Disable() {
	_m.Called()
}

// Execute provides a mock function with given fields: ctx, wg
func (_m *MockKafkaConsumerProcessorInterface) Execute(ctx context.Context, wg *sync.WaitGroup) {
	_m.Called(ctx, wg)
}

type mockConstructorTestingTNewMockKafkaConsumerProcessorInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockKafkaConsumerProcessorInterface creates a new instance of MockKafkaConsumerProcessorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockKafkaConsumerProcessorInterface(t mockConstructorTestingTNewMockKafkaConsumerProcessorInterface) *MockKafkaConsumerProcessorInterface {
	mock := &MockKafkaConsumerProcessorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
