// Code generated by mockery v2.20.2. DO NOT EDIT.

package framework

import (
	context "context"

	events "github.com/kneu-messenger-pigeon/events"
	mock "github.com/stretchr/testify/mock"

	sync "sync"
)

// MockClientControllerInterface is an autogenerated mock type for the ClientControllerInterface type
type MockClientControllerInterface struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, wg
func (_m *MockClientControllerInterface) Execute(ctx context.Context, wg *sync.WaitGroup) {
	_m.Called(ctx, wg)
}

// ScoreChangedAction provides a mock function with given fields: event
func (_m *MockClientControllerInterface) ScoreChangedAction(event *events.ScoreChangedEvent) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.ScoreChangedEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserAuthorizedAction provides a mock function with given fields: event
func (_m *MockClientControllerInterface) UserAuthorizedAction(event *events.UserAuthorizedEvent) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.UserAuthorizedEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockClientControllerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockClientControllerInterface creates a new instance of MockClientControllerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockClientControllerInterface(t mockConstructorTestingTNewMockClientControllerInterface) *MockClientControllerInterface {
	mock := &MockClientControllerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
