// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EventHandlerInterface is an autogenerated mock type for the EventHandlerInterface type
type EventHandlerInterface struct {
	mock.Mock
}

// Commit provides a mock function with given fields:
func (_m *EventHandlerInterface) Commit() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetExpectedEventType provides a mock function with given fields:
func (_m *EventHandlerInterface) GetExpectedEventType() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// GetExpectedMessageKey provides a mock function with given fields:
func (_m *EventHandlerInterface) GetExpectedMessageKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Handle provides a mock function with given fields: event
func (_m *EventHandlerInterface) Handle(event interface{}) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEventHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewEventHandlerInterface creates a new instance of EventHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEventHandlerInterface(t mockConstructorTestingTNewEventHandlerInterface) *EventHandlerInterface {
	mock := &EventHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
