// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ScoreChangedStateStorageInterface is an autogenerated mock type for the ScoreChangedStateStorageInterface type
type ScoreChangedStateStorageInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: studentId, lessonId
func (_m *ScoreChangedStateStorageInterface) Get(studentId uint, lessonId uint) string {
	ret := _m.Called(studentId, lessonId)

	var r0 string
	if rf, ok := ret.Get(0).(func(uint, uint) string); ok {
		r0 = rf(studentId, lessonId)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Set provides a mock function with given fields: studentId, lessonId, state
func (_m *ScoreChangedStateStorageInterface) Set(studentId uint, lessonId uint, state string) {
	_m.Called(studentId, lessonId, state)
}

type mockConstructorTestingTNewScoreChangedStateStorageInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewScoreChangedStateStorageInterface creates a new instance of ScoreChangedStateStorageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewScoreChangedStateStorageInterface(t mockConstructorTestingTNewScoreChangedStateStorageInterface) *ScoreChangedStateStorageInterface {
	mock := &ScoreChangedStateStorageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
