// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	events "github.com/kneu-messenger-pigeon/events"

	mock "github.com/stretchr/testify/mock"

	scoreApi "github.com/kneu-messenger-pigeon/score-api"
)

// ScoreChangeEventComposerInterface is an autogenerated mock type for the ScoreChangeEventComposerInterface type
type ScoreChangeEventComposerInterface struct {
	mock.Mock
}

// BothPreviousScoresSaved provides a mock function with given fields: event
func (_m *ScoreChangeEventComposerInterface) BothPreviousScoresSaved(event *events.ScoreChangedEvent) bool {
	ret := _m.Called(event)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*events.ScoreChangedEvent) bool); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Compose provides a mock function with given fields: event, currentScore
func (_m *ScoreChangeEventComposerInterface) Compose(event *events.ScoreChangedEvent, currentScore *scoreApi.Score) *scoreApi.Score {
	ret := _m.Called(event, currentScore)

	var r0 *scoreApi.Score
	if rf, ok := ret.Get(0).(func(*events.ScoreChangedEvent, *scoreApi.Score) *scoreApi.Score); ok {
		r0 = rf(event, currentScore)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*scoreApi.Score)
		}
	}

	return r0
}

// SavePreviousScore provides a mock function with given fields: event
func (_m *ScoreChangeEventComposerInterface) SavePreviousScore(event *events.ScoreChangedEvent) {
	_m.Called(event)
}

type mockConstructorTestingTNewScoreChangeEventComposerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewScoreChangeEventComposerInterface creates a new instance of ScoreChangeEventComposerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewScoreChangeEventComposerInterface(t mockConstructorTestingTNewScoreChangeEventComposerInterface) *ScoreChangeEventComposerInterface {
	mock := &ScoreChangeEventComposerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
