// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sync "sync"
)

// UserCountMetricsSyncerInterface is an autogenerated mock type for the UserCountMetricsSyncerInterface type
type UserCountMetricsSyncerInterface struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, wg
func (_m *UserCountMetricsSyncerInterface) Execute(ctx context.Context, wg *sync.WaitGroup) {
	_m.Called(ctx, wg)
}

type mockConstructorTestingTNewUserCountMetricsSyncerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserCountMetricsSyncerInterface creates a new instance of UserCountMetricsSyncerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserCountMetricsSyncerInterface(t mockConstructorTestingTNewUserCountMetricsSyncerInterface) *UserCountMetricsSyncerInterface {
	mock := &UserCountMetricsSyncerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
