// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserLogoutHandlerInterface is an autogenerated mock type for the UserLogoutHandlerInterface type
type UserLogoutHandlerInterface struct {
	mock.Mock
}

// Handle provides a mock function with given fields: clientUserId
func (_m *UserLogoutHandlerInterface) Handle(clientUserId string) error {
	ret := _m.Called(clientUserId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(clientUserId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUserLogoutHandlerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserLogoutHandlerInterface creates a new instance of UserLogoutHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserLogoutHandlerInterface(t mockConstructorTestingTNewUserLogoutHandlerInterface) *UserLogoutHandlerInterface {
	mock := &UserLogoutHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
